### PR TITLE
Add CC-BY-4.0 LICENSE for documentation and image

### PR DESCRIPTION
**Pull request by C-BJ**
Unified with [Webpage](https://github.com/erg-lang/erg-lang.github.io)'s LICENSE

### CODE REVIEW

**Comment by mtshiba** [comment]
Wouldn't this make it impossible for GitHub to identify licenses?

スクリーンショット 2022-08-20 212059

**Comment by C-BJ** [comment]
> Wouldn't this make it impossible for GitHub to identify licenses? @C-BJ
> 
> スクリーンショット 2022-08-20 212059

Yes, do you have a better way?

**Comment by mtshiba** [comment]
Suppose someone considers using the Erg code base in the future. That person looks at the license notice on GitHub and may think, "Is this project using the original license? This looks like a hassle," and may give up without taking a closer look at the file.

And since the license probably doesn't need to be translated, there is no particular problem with leaving it in the directory root.

Also, it's enough to mention in the README that the documentation is provided under CC BY 4.0.

**Comment by C-BJ** [comment]
> Suppose someone considers using the Erg code base in the future. That person looks at the license notice on GitHub and may think, "Is this project using the original license? This looks like a hassle," and may give up without taking a closer look at the file.
> 
> And since the license probably doesn't need to be translated, there is no particular problem with leaving it in the directory root.
> 
> Also, it's enough to mention in the README that the documentation is provided under CC BY 4.0.

It is worth mentioning that even if GitHub recognizes Apache 2.0, it may not be the source license, such as swift

**Comment by mtshiba** [comment]
Well, I think it would be better to know at a glance from the file name.

**Comment by mtshiba** [comment]
Wouldn't it be better to write what is written in [LICENSE](https://github.com/erg-lang/erg/pull/68/files#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7) at the end of the README? That way, it can be translated into each language version and the cost of synchronization will not increase.

**Comment by C-BJ** [comment]
People only need to know that the code is MIT + Apache 2.0,

**Comment by C-BJ** [comment]
People all over the world know the meaning of these two licenses

**Comment by mtshiba** [comment]
Of course that would be true, but I think the current situation displayed in the sidebar is better.
I only adopted the dual license in accordance with Rust's culture, not because I think that both must be displayed. As long as one or the other is displayed, it is fine.

**Comment by C-BJ** [comment]
> Of course that would be true, but I think the current situation displayed in the sidebar is better. I only adopted the dual license in accordance with Rust's culture, I don't think that both must be displayed. As long as one or the other is displayed, it is fine.

Dual licenses are really better than MIT or Apache alone

**Comment by mtshiba** [comment]
Yes, it is. I was just mentioning the issue of only one of the licenses being displayed.

a

**Comment by mtshiba** [comment]
Thanks!

**Pull request merged**
