### PR TITLE
Implement `Dict`

### PR DESCRIPTION
**Pull request by mtshiba**
The following new implementations have been included to implement Dict.

* `Type::ProjMethod`: This allows for advanced type operations such as `{Int: Str}[Int]` (== Str).

And with this, `erg_type::ConstSubr` now depends on `Context` in `erg_compiler`, so the `erg_type` crate has been downgraded to a module.

### CODE REVIEW

**Comment by GreasySlug** [comment]
```sh
>>> a = {"a": 1, "b": 23, "c": 2} 

>>> a["a"]
1
>>> a["b"] 
23
>>> a["c"] 
2
>>> a["d"] 
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', compiler\erg_compiler\context\initialize\const_func.rs:211:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', src\main.rs:64:Traceback (most recent call last):
22  File "<string>", line 18, in <module>

ConnectionAbortedError: [WinError 10053] 確立された接続がホスト コンピューターのソウトウェアによって中止 
されました。
```

**Comment by mtshiba** [comment]
```sh
>>> a = {"a": 1}

>>> a["b"]
Error[#0226]: File <stdin>, line 1, in <module>
1│ a["b"]
   ^
IndexError: {{"a", }: {1, }} has no key ?T(:> {"b", })
>>>
```

😎

**Comment by GreasySlug** [comment]
This is a slight problem, but it seems that if the key of dict is Range, it is not parsed properly.

```sh
>>> {"a": 1..<3}
{'a': range(1, 3)}
>>> {1..<3: "a"}
{3: 'a'}
```

**Comment by mtshiba** [comment]
```console
>>> {1+1: 0}
{1: 0}
>>>
```

The parsing bug seems to occur when the Dict key is a compound expression.

**Comment by mtshiba** [comment]
Fixed.

**Comment by GreasySlug** [comment]
You're so quick to fix it!!
Currently *Range` is buggy, so I can't check as a key value of `Dict`, but it seems to be fixed as it works with compound expressions.

**Comment by mtshiba** [comment]
スクリーンショット 2022-10-12 183342

**Pull request merged**
