### PR TITLE
Add `=>` proc and `->` func  hint

### LINKED ISSUE #242: Type mismatch between Procedure & Function
```erg
for! [1, 2, 3], i ->
    print! i
    print! i
```

The above code will output

```console
Error[#1070]: File test.er, line 12..14, <module>

12 | for! [1, 2, 3], i ->
   :                 ----
13 |     print! i
   : ------------
14 |     print! i
   : ------------
   :            |- expected: (?T(: Type)) => NoneType
   :            `- but found: (i: ?1(<: Ref(Obj))) -> NoneType
```

However, this is not enough to determine the cause of the error. It should give a hint that an anonymous function should be changed to a procedure (-> should be changed to =>).

### PR DESCRIPTION
**Pull request by GreasySlug**
Fixes #242 .

Each now gives a hint in case of an error.

~~Currently the text is white, should I add a color?~~ Added

@mtshiba

### CODE REVIEW

**Comment by mtshiba** [comment]
I think "hint: use => instead of ->" is better.

Also, since functions are a subtype of procedures (functions are procedures without side effects), there is no need to consider the case of expect: Proc, found: Func.

**Comment by GreasySlug** [comment]
proc_hint

**Comment by mtshiba** [comment]
Oh, sorry.

I thought something was wrong, but the type checker contained a bug.

As I thought, expect: Proc, found: Func is OK.

```
10.times!(() => print! 1) # OK
10.times!(() -> log 1) # OK
i.update! x -> x + 1 # OK
i.update! x => x + 1 # NG
```

I just pushed the fix to main.

**Comment by GreasySlug** [comment]
It was causing conflict and I solved that.

**Comment by GreasySlug** [comment]
`for!` will result in a side-effect error, and `update!` will result in an error if it is a procedure with an argument that takes an anonymous function

I don't know of any examples of receiving other functions and procedures, so I have not been able to confirm it.

hint

**Comment by mtshiba** [comment]
You can define and check them.

https://erg-lang.org/web-ide/?code=GYAgDghAXCAUCSA7ALiAvAPhE5BKdIAcgPaICmAsAFADmIwMCKIAtFjvmkaZVdaAEtWWAfxBDM46nSFsptcehFA

**Comment by GreasySlug** [comment]
Thank you
Check these and only `g i => i` will cause an error.

**Pull request merged**
