### PR TITLE
Possible to localized to help commands

### PR DESCRIPTION
**Pull request by GreasySlug**
When feature flag is specified, comments are switched to the respective language.
This can be used to switch help commands as well.
Translate from Japanese text to EN and CH.

- [x] Help command review
    - [x] JA
    - [x] EN
    - [x] zh_CN
    - [x] zh_TW
- [x] Mode help command review
    - [x] JA
    - [x] EN
    - [x] zh_CN
    - [x] zh_TW

Unwrap() is often used to parse arguments, causing panic with wrong arguments.

Changes proposed in this PR:
- Possible to localize to help command
- Add help_message.rs
- Error handling of args parsing (Shouldn't this be included?)

@mtshiba

### CODE REVIEW

**Comment by C-BJ** [comment]
We need to write relevant development documents @GreasySlug

**Comment by GreasySlug** [comment]
> We need to write relevant development documents @GreasySlug

That's right.

I'm going to make how to localize help commands.

**Comment by GreasySlug** [comment]
Translated Ja to Ch and En.
Especially, I cannot correct Chinese sentences, so I would appreciate your confirmation.

**Comment by C-BJ** [comment]
Is this PR completed? @GreasySlug

**Comment by GreasySlug** [comment]
Drafts have been completed, @C-BJ

**Pull request merged**
