### PR TITLE
Fixed broken link in Syntax Documentation

### PR DESCRIPTION
**Pull request by ytoml**
Some links in `doc/JA/syntax` were broken (they were referring to `.html` rather than `.md`), thus fixed.

### CODE REVIEW

**Comment by ytoml** [comment]
Could you wait merging? I found there are more misses (e.g. `10_array.md` refers to `11_dict.md`).

**Comment by ytoml** [comment]
> Could you wait merging? I found there are more misses (e.g. `10_array.md` refers to `11_dict.md`).
  
Error of same type were also found in EN doc, thus I modified PR title.
They fill be fixed soon.

**Comment by ytoml** [comment]
I checked all footer links in`doc/(EN|JA)/syntax`.

**Comment by mtshiba** [comment]
Thanks!

**Pull request merged**
