### PR TITLE
Change the wrong placement of pull_request_template.md

### PR DESCRIPTION
**Pull request by C-BJ**
@mtshiba

### CODE REVIEW

**Comment by mtshiba** [comment]
Placing it in the location would seem to allow for multiple PR templates (though I have only prepared one yet).

image

**Comment by C-BJ** [comment]
> Placing it in the location would seem to allow for multiple PR templates (though I have only prepared one yet).
> 
> image

A single template should not be placed in a folder

**Comment by C-BJ** [comment]
image
@mtshiba

**Comment by mtshiba** [comment]
Now I created a template for bug fix and that for implementing new features, is it still invalid?

**Comment by C-BJ** [comment]
> Now I created a template for bug fix and that for implementing new features, is it still invalid?

Yes

**Comment by mtshiba** [comment]
I see. It seems that if there are multiple PR templates here, you have to add `?template=template_name.md` to the PR creation URL.
This is a hassle, so let's not do this.

**Pull request merged**
