### PR TITLE
Docs: add sync_to_summary.py and sync

### PR DESCRIPTION
**Pull request by toddlerer**
I created the Python script that automatically generates `SUMMARY.md` from the title of Markdown files. I tried to create this in Erg, but it still seemed too difficult. Currently summary is sorted alphabetically by filename. But this script may not work well on Windows.
`SUMMARY.md` has been rewritten, please check and change a title of markdown files if necessary.

@mtshiba @C-BJ

### CODE REVIEW

**Comment by C-BJ** [comment]
I made some changes to the title of the Chinese document, please pull down main in to your branch and re-run the script for zh_CN and zh_TW @toddlerer

**Comment by toddlerer** [comment]
@C-BJ Thank you. Reflected.

**Comment by C-BJ** [comment]
@toddlerer i have a question, Are the documents that update commit hash translated completely? I just want to make sure that there is nothing wrong, and I'm using mobile phone now, I can't check the documents.

**Comment by toddlerer** [comment]
@C-BJ Are you talking about bdfdbfb36f7e24ab9d8d6a3988049d37f1ee4cd0 commit? I haven't fully checked the content, but the original documents were badged `up to date`, so I updated it.

**Comment by C-BJ** [comment]
> @C-BJ Are you talking about [bdfdbfb](https://github.com/erg-lang/erg/commit/bdfdbfb36f7e24ab9d8d6a3988049d37f1ee4cd0) commit? I haven't fully checked the content, but the original documents were badged `up to date`, so I updated it.

Ok

**Comment by C-BJ** [comment]
@mtshiba @toddlerer I think this PR can be merged, But I'm thinking about the possibility of adding this python script to CI, and if the changes are limited to documents, checks and test will not be run. I think this is possible, but I'm not familiar with these.

**Comment by C-BJ** [comment]
Please pull main and run the scripts in all languages again. After completion, the PR can be merged.

**Comment by C-BJ** [comment]
I want to make some changes, and the PR can merge later today.

**Pull request merged**
