### PR TITLE
[WIP] Added normal tuple type structure and parser

### PR DESCRIPTION
**Pull request by GreasySlug**
related:  #34

- [x] add ast struct of normal type tuple
    - [x] NormalTuple use `paren: Option<Token, Token>`
- [x] add parser with parentheses
- [ ] add parser without parentheses
~~add type checking (Do you think this should not be included?)~~

### CODE REVIEW

**Comment by mtshiba** [comment]
Since `Args` has `paren: Option<Token, Token>` (which has information about the parentheses), `NormalTuple` should simply wrap it.

And type checking would probably require a new mechanism, so no need to implement it. I will do it.

**Comment by mtshiba** [comment]
For parsing tuples, we can modify try_reduce_call_or_acc to try_reduce_call_or_acc_or_tuple.
This is because, for example, when reading the identifier `f`, there are only three possible grammars at this point.

* f is an `Accessor`
* f is a callee
* f is the first element of a tuple

In other words, immediately after reducing `f`, Parser calls  `opt_reduce_args`, but before this, it should be checked if there is a `,` and if so, Parser should move on to reducing the tuple.

**Comment by GreasySlug** [comment]
Perhaps those are the pieces of information I wanted to know.
If I cannot achieve tuple without parentheses, is it possible to create it as a separate Issue and create the PR again?

**Comment by mtshiba** [comment]
Ok, but perhaps parentheses are not essential to tuples. A tuple without parentheses is actually the standard form.
If you write `1, 2`, it is a standard tuple, `(1, 2)` is just a tuple with parentheses. It is exactly the same as `(1+1)` and so on.

**Comment by mtshiba** [comment]
Thank you @GreasySlug !

**Pull request merged**
