### PR TITLE
Add stream operator

### LINKED ISSUE #170: Add stream operator
See [|> operator](https://github.com/erg-lang/erg/blob/main/doc/EN/API/special.md#obj-c-callable) for details.

### PR DESCRIPTION
**Pull request by ytoml**
Fixes #170 .

Hi, I implemented stream operator.

Changes proposed in this PR:
- Stream operator is enabled, for example:
```erg
Point = Class {x = Int; y = Int}
Point.
    new x, y = Point::__new__ {x; y}
    norm self = self::x**2 + self::y**2

print! 1 |> Point.new(10) |> .norm() # prints 101
```

@mtshiba

### CODE REVIEW

**Comment by mtshiba** [comment]
Thank you. But I found a mistake in the parsing.

```python
print!(1 + 1 |> f())
print!(1 + 1 |> .abs())
```

should be

```python
print!(f(1+1))
print!((1+1).abs())
```

but we got

image

**Comment by ytoml** [comment]
Thanks, I fixed it by collecting binop(`Expr Op Expr`) into single `Expr` before parsing Pipe, in order to confirm that all `BinOp`s precede pipes.

**Comment by ytoml** [comment]
`stream.er`:
スクリーンショット 2022-11-16 13 08 27

**Comment by mtshiba** [comment]
Thank you!

**Pull request merged**
