### PR TITLE
ci: update yml

### PR DESCRIPTION
**Pull request by C-BJ**
Changes proposed in this PR:

- Rename `rust.yml` -> `ci.yml`
- Test is no longer run when the corresponding platform fails to compile
- Use `cargo check` rather than `cargo build` in build and check

@mtshiba

### CODE REVIEW

**Comment by mtshiba** [comment]
Why tests and builds are run independently is to reduce CI run time.

This change should basically make CI time worse (though there will be a cache effect).

**Comment by C-BJ** [comment]
I see, But I don't understand the purpose of build and check

**Comment by toddlerer** [comment]
The reason I used `cargo build` instead of `cargo check` is that `cargo check` does not allow for some checks([ref](https://doc.rust-lang.org/cargo/commands/cargo-check.html#:~:text=Some%20diagnostics%20and%20errors%20are%20only%20emitted%20during%20code%20generation%2C%20so%20they%20inherently%20won%27t%20be%20reported%20with%20cargo%20check.)). I didn't leave my intentions in a comment out, so I guess I didn't get the message.

**Comment by C-BJ** [comment]
I mean, why don't we just test it? without build and check

**Comment by mtshiba** [comment]
The advantage is that when CI fails, it is easy to see whether the build or the test has failed.

**Comment by C-BJ** [comment]
I see

**Pull request closed without merging**
