### PR TITLE
Move lib to the root directory

### PR DESCRIPTION
**Pull request by C-BJ**
Since els is integrated into the erg, lib is no longer needed as a dependency, so you can move lib to where it should be

@mtshiba

### CODE REVIEW

**Comment by mtshiba** [comment]
The reason lib is in erg_compiler is because erg_compiler is a standalone crate that depends on lib.
els is not relevant.

**Comment by C-BJ** [comment]
Yes, I know.

**Comment by C-BJ** [comment]
If change the location of lib, is there any problem? @mtshiba

**Comment by mtshiba** [comment]
`cargo install erg_compiler` must work properly. Means lib must be installed.

I don't know if cargo allows specifying resources like  `../../`. Is this allowed?

**Comment by C-BJ** [comment]
> `cargo install erg_compiler` must work properly. Means lib must be installed.
> 
> I don't know if cargo allows specifying resources like `../../`. Is this allowed?

I'll go and see.

**Comment by C-BJ** [comment]
btw, Do you think the name of the compiler folder in the root directory should be changed, such as core

**Comment by mtshiba** [comment]
I'm considering renaming the  `compiler` directory to something like `crates`.

**Comment by C-BJ** [comment]
yeah, great

**Comment by C-BJ** [comment]
But after rewriting it with erg, isn't it a strange name

**Comment by mtshiba** [comment]
Renaming the directory is a trivial matter, as it would be a massive change if the erg were to be rewritten by itself.

**Comment by C-BJ** [comment]
yeah

**Comment by C-BJ** [comment]
I think I've done it @mtshiba

**Comment by C-BJ** [comment]
I successfully generated `lib` in `.erg` by compiling erg_compiler only

**Comment by C-BJ** [comment]
wait

**Comment by mtshiba** [comment]
I tried to publish `erg_compiler`.
After all, it seems that such a specification is not possible.

スクリーンショット_20230114_154751

**Comment by mtshiba** [comment]
Same result.

How about making a small dummy crate to test it out?

**Comment by C-BJ** [comment]
ok

**Pull request closed without merging**
